### ISSUE TITLE
Some Clarification on the new VariabilityGalaxy [1.0.0-86-g4e41113+4]

### ISSUE THREAD

**Issue by JPGlaser** [lsst/sims_catUtils#12]
Hey @SimonKrughoff & @danielsf,

This is Joe Glaser. Hope you all are doing well. Since my questions have moved from Obsim integration to the Variability mixin, I figured it would probably be a good idea to shift the discussion to a new topic. So I have the latest release from you guys running, and I have to say I am enjoying some of the subtle changes.

As a quick inquiry, I see that the VariableGalaxies now outputs colname and delta_colname from the galaxy database. Now it says the mixin automatically adds the delta_colname to the colname. If that's the case, can I just readout the colname and be done?

Also, is it required for me to write each catalog into a text before I can read it in as an array? If so, is there any way to output the catalogs as .FITS files?

Thanks in advance.

~ Joe

**Comment by danielsf** [comment]
Hi Joe,

Glad you found the new release.  Sorry I have been so slow documenting it.

Regarding the new Vairability mixin:

As long as your InstanceCatalog class inherits from the variability mixin that defines the getter for delta_colname then, yes, just asking the InstanceCatalog class to output delta_colname will add the variability in.

As far as accessing the Catalogs: there is no code to output them as FITS files.  InstanceCatalog has a member method iter_catalog() that returns an iterator over the catalog, so you could do something like

`
myCat = CatalogClass()
myIter = myCat.iter_catalog()
for line in myIter:
    do things with the lines in your catalog
'

does that help?

-- Scott
